In [6]:
import polars as pl
import polars.selectors as cs

In [ ]:
df_scipy_500 = pl.read_csv("results_mtp_scipy_bfgs_500.csv").drop(
    "success", "final_loss"
)
df_scipy_1000 = pl.read_csv("results_mtp_scipy_bfgs_1000.csv").drop(
    "success", "final_loss"
)
df_scipy_001 = pl.read_csv("results_mtp_scipy_bfgs_001.csv").drop(
    "success", "final_loss"
)

df_mlip_500 = pl.read_csv(
    "/Users/peterzarenkov/projects/course_work/optimization_methods_MLP/task1/results/results_mtp.csv"
)

def display_ensemble_stats(df: pl.DataFrame, name: str):
    metrics = df.select(cs.numeric())
    display(pl.DataFrame({"stat": [name]}).hstack(metrics.select(pl.all().mean())))
    display(pl.DataFrame({"stat": [f"{name}_std"]}).hstack(metrics.select(pl.all().std())))

Срванение встроенного BFGS и scipy на 500 итерациях

In [8]:
display(df_scipy_500)
display(df_mlip_500)

shape: (5, 9)
┌─────────┬─────────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬─────┐
│ pot_num ┆ train_energ ┆ train_ener ┆ train_forc ┆ … ┆ val_energy ┆ val_forces ┆ train_time ┆ nit │
│ ---     ┆ y_rmse      ┆ gy_atom_rm ┆ es_rmse    ┆   ┆ _atom_rmse ┆ _rmse      ┆ ---        ┆ --- │
│ i64     ┆ ---         ┆ se         ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64        ┆ i64 │
│         ┆ f64         ┆ ---        ┆ f64        ┆   ┆ f64        ┆ f64        ┆            ┆     │
│         ┆             ┆ f64        ┆            ┆   ┆            ┆            ┆            ┆     │
╞═════════╪═════════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═════╡
│ 1       ┆ 136.511061  ┆ 4.265971   ┆ 92.075705  ┆ … ┆ 4.646041   ┆ 144.855572 ┆ 319.594795 ┆ 500 │
│ 2       ┆ 0.399775    ┆ 0.012493   ┆ 0.339653   ┆ … ┆ 0.020972   ┆ 0.791595   ┆ 318.626857 ┆ 500 │
│ 3       ┆ 0.163806    ┆ 0.005119   ┆ 0.149562   ┆ … ┆ 0.009221   ┆ 0.292811   ┆ 318.176145 ┆ 500 │
│ 4       ┆ 0.572485    ┆ 0.01789    ┆ 0.407298   ┆ … ┆ 0.039614   ┆ 0.739955   ┆ 331.07167  ┆ 500 │
│ 5       ┆ 0.473086    ┆ 0.014784   ┆ 0.395366   ┆ … ┆ 0.025413   ┆ 0.681473   ┆ 324.40331  ┆ 500 │
└─────────┴─────────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴─────┘

shape: (5, 8)
┌─────────┬────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┐
│ pot_num ┆ train_ener ┆ train_ener ┆ train_forc ┆ val_energy ┆ val_energy ┆ val_force ┆ train_tim │
│ ---     ┆ gy_rmse    ┆ gy_atom_rm ┆ es_rmse    ┆ _rmse      ┆ _atom_rmse ┆ s_rmse    ┆ e         │
│ i64     ┆ ---        ┆ se         ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│         ┆ f64        ┆ ---        ┆ f64        ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
│         ┆            ┆ f64        ┆            ┆            ┆            ┆           ┆           │
╞═════════╪════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╡
│ 1       ┆ 0.09327    ┆ 0.002915   ┆ 0.077761   ┆ 0.161312   ┆ 0.005041   ┆ 0.120006  ┆ 339.14160 │
│         ┆            ┆            ┆            ┆            ┆            ┆           ┆ 7         │
│ 2       ┆ 0.077083   ┆ 0.002409   ┆ 0.074072   ┆ 0.124319   ┆ 0.003885   ┆ 0.113015  ┆ 364.96913 │
│         ┆            ┆            ┆            ┆            ┆            ┆           ┆ 7         │
│ 3       ┆ 0.086659   ┆ 0.002708   ┆ 0.07386    ┆ 0.12994    ┆ 0.004061   ┆ 0.110455  ┆ 366.34247 │
│         ┆            ┆            ┆            ┆            ┆            ┆           ┆ 4         │
│ 4       ┆ 0.07983    ┆ 0.002495   ┆ 0.060698   ┆ 0.137284   ┆ 0.00429    ┆ 0.089316  ┆ 369.00964 │
│         ┆            ┆            ┆            ┆            ┆            ┆           ┆ 8         │
│ 5       ┆ 0.099781   ┆ 0.003118   ┆ 0.074714   ┆ 0.173422   ┆ 0.005419   ┆ 0.115487  ┆ 359.96218 │
└─────────┴────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┘

Среднее значение ошибки и разброс для scipy BFGS и встроенного.

In [9]:
display_ensemble_stats(df_scipy_500, "scipy_500_mean")
display_ensemble_stats(df_mlip_500, "mlip_500_mean")

shape: (1, 10)
┌────────────┬─────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────┐
│ stat       ┆ pot_num ┆ train_ener ┆ train_ener ┆ … ┆ val_energy ┆ val_forces ┆ train_tim ┆ nit   │
│ ---        ┆ ---     ┆ gy_rmse    ┆ gy_atom_rm ┆   ┆ _atom_rmse ┆ _rmse      ┆ e         ┆ ---   │
│ str        ┆ f64     ┆ ---        ┆ se         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ f64   │
│            ┆         ┆ f64        ┆ ---        ┆   ┆ f64        ┆ f64        ┆ f64       ┆       │
│            ┆         ┆            ┆ f64        ┆   ┆            ┆            ┆           ┆       │
╞════════════╪═════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════╡
│ scipy_500_ ┆ 3.0     ┆ 27.624042  ┆ 0.863251   ┆ … ┆ 0.948252   ┆ 29.472281  ┆ 322.37455 ┆ 500.0 │
│ mean       ┆         ┆            ┆            ┆   ┆            ┆            ┆ 5         ┆       │
└────────────┴─────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────┘

shape: (1, 10)
┌────────────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬─────┐
│ stat       ┆ pot_num  ┆ train_ener ┆ train_ener ┆ … ┆ val_energy ┆ val_forces ┆ train_time ┆ nit │
│ ---        ┆ ---      ┆ gy_rmse    ┆ gy_atom_rm ┆   ┆ _atom_rmse ┆ _rmse      ┆ ---        ┆ --- │
│ str        ┆ f64      ┆ ---        ┆ se         ┆   ┆ ---        ┆ ---        ┆ f64        ┆ f64 │
│            ┆          ┆ f64        ┆ ---        ┆   ┆ f64        ┆ f64        ┆            ┆     │
│            ┆          ┆            ┆ f64        ┆   ┆            ┆            ┆            ┆     │
╞════════════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═════╡
│ scipy_500_ ┆ 1.581139 ┆ 60.86988   ┆ 1.902184   ┆ … ┆ 2.067155   ┆ 64.50152   ┆ 5.457898   ┆ 0.0 │
│ mean_std   ┆          ┆            ┆            ┆   ┆            ┆            ┆            ┆     │
└────────────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴─────┘

shape: (1, 9)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stat       ┆ pot_num ┆ train_ene ┆ train_ene ┆ … ┆ val_energ ┆ val_energ ┆ val_force ┆ train_tim │
│ ---        ┆ ---     ┆ rgy_rmse  ┆ rgy_atom_ ┆   ┆ y_rmse    ┆ y_atom_rm ┆ s_rmse    ┆ e         │
│ str        ┆ f64     ┆ ---       ┆ rmse      ┆   ┆ ---       ┆ se        ┆ ---       ┆ ---       │
│            ┆         ┆ f64       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│            ┆         ┆           ┆ f64       ┆   ┆           ┆ f64       ┆           ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ mlip_500_m ┆ 3.0     ┆ 0.087325  ┆ 0.002729  ┆ … ┆ 0.145255  ┆ 0.004539  ┆ 0.109656  ┆ 359.88500 │
│ ean        ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9         │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (1, 9)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stat      ┆ pot_num  ┆ train_ene ┆ train_ene ┆ … ┆ val_energ ┆ val_energ ┆ val_force ┆ train_tim │
│ ---       ┆ ---      ┆ rgy_rmse  ┆ rgy_atom_ ┆   ┆ y_rmse    ┆ y_atom_rm ┆ s_rmse    ┆ e         │
│ str       ┆ f64      ┆ ---       ┆ rmse      ┆   ┆ ---       ┆ se        ┆ ---       ┆ ---       │
│           ┆          ┆ f64       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│           ┆          ┆           ┆ f64       ┆   ┆           ┆ f64       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ mlip_500_ ┆ 1.581139 ┆ 0.009381  ┆ 0.000293  ┆ … ┆ 0.02114   ┆ 0.000661  ┆ 0.011904  ┆ 12.053017 │
│ mean_std  ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

Сравниение ошибок scip BFGS для 500 итераций и 1000

In [10]:
display(df_scipy_500)
display(df_scipy_1000)

shape: (5, 9)
┌─────────┬─────────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬─────┐
│ pot_num ┆ train_energ ┆ train_ener ┆ train_forc ┆ … ┆ val_energy ┆ val_forces ┆ train_time ┆ nit │
│ ---     ┆ y_rmse      ┆ gy_atom_rm ┆ es_rmse    ┆   ┆ _atom_rmse ┆ _rmse      ┆ ---        ┆ --- │
│ i64     ┆ ---         ┆ se         ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64        ┆ i64 │
│         ┆ f64         ┆ ---        ┆ f64        ┆   ┆ f64        ┆ f64        ┆            ┆     │
│         ┆             ┆ f64        ┆            ┆   ┆            ┆            ┆            ┆     │
╞═════════╪═════════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═════╡
│ 1       ┆ 136.511061  ┆ 4.265971   ┆ 92.075705  ┆ … ┆ 4.646041   ┆ 144.855572 ┆ 319.594795 ┆ 500 │
│ 2       ┆ 0.399775    ┆ 0.012493   ┆ 0.339653   ┆ … ┆ 0.020972   ┆ 0.791595   ┆ 318.626857 ┆ 500 │
│ 3       ┆ 0.163806    ┆ 0.005119   ┆ 0.149562   ┆ … ┆ 0.009221   ┆ 0.292811   ┆ 318.176145 ┆ 500 │
│ 4       ┆ 0.572485    ┆ 0.01789    ┆ 0.407298   ┆ … ┆ 0.039614   ┆ 0.739955   ┆ 331.07167  ┆ 500 │
│ 5       ┆ 0.473086    ┆ 0.014784   ┆ 0.395366   ┆ … ┆ 0.025413   ┆ 0.681473   ┆ 324.40331  ┆ 500 │
└─────────┴─────────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴─────┘

shape: (5, 9)
┌─────────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬──────┐
│ pot_num ┆ train_ener ┆ train_ener ┆ train_forc ┆ … ┆ val_energy ┆ val_forces ┆ train_time ┆ nit  │
│ ---     ┆ gy_rmse    ┆ gy_atom_rm ┆ es_rmse    ┆   ┆ _atom_rmse ┆ _rmse      ┆ ---        ┆ ---  │
│ i64     ┆ ---        ┆ se         ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64        ┆ i64  │
│         ┆ f64        ┆ ---        ┆ f64        ┆   ┆ f64        ┆ f64        ┆            ┆      │
│         ┆            ┆ f64        ┆            ┆   ┆            ┆            ┆            ┆      │
╞═════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪══════╡
│ 1       ┆ 136.510919 ┆ 4.265966   ┆ 92.075524  ┆ … ┆ 4.646022   ┆ 144.855077 ┆ 586.214199 ┆ 702  │
│ 2       ┆ 0.357038   ┆ 0.011157   ┆ 0.261757   ┆ … ┆ 0.018781   ┆ 0.5239     ┆ 586.287035 ┆ 1000 │
│ 3       ┆ 0.08892    ┆ 0.002779   ┆ 0.075821   ┆ … ┆ 0.004844   ┆ 0.126361   ┆ 580.527048 ┆ 1000 │
│ 4       ┆ 0.477969   ┆ 0.014937   ┆ 0.260945   ┆ … ┆ 0.029617   ┆ 0.540483   ┆ 591.546148 ┆ 1000 │
│ 5       ┆ 0.426299   ┆ 0.013322   ┆ 0.340675   ┆ … ┆ 0.025144   ┆ 1.321492   ┆ 599.936691 ┆ 678  │
└─────────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴──────┘

Видим, что для некоторых потенциалов из ансамбля обучение останавливалось раньше и ошибки упали.

In [11]:
display_ensemble_stats(df_scipy_500, "scipy_500_mean")
display_ensemble_stats(df_scipy_1000, "scipy_1000_mean")

shape: (1, 10)
┌────────────┬─────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────┐
│ stat       ┆ pot_num ┆ train_ener ┆ train_ener ┆ … ┆ val_energy ┆ val_forces ┆ train_tim ┆ nit   │
│ ---        ┆ ---     ┆ gy_rmse    ┆ gy_atom_rm ┆   ┆ _atom_rmse ┆ _rmse      ┆ e         ┆ ---   │
│ str        ┆ f64     ┆ ---        ┆ se         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ f64   │
│            ┆         ┆ f64        ┆ ---        ┆   ┆ f64        ┆ f64        ┆ f64       ┆       │
│            ┆         ┆            ┆ f64        ┆   ┆            ┆            ┆           ┆       │
╞════════════╪═════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════╡
│ scipy_500_ ┆ 3.0     ┆ 27.624042  ┆ 0.863251   ┆ … ┆ 0.948252   ┆ 29.472281  ┆ 322.37455 ┆ 500.0 │
│ mean       ┆         ┆            ┆            ┆   ┆            ┆            ┆ 5         ┆       │
└────────────┴─────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────┘

shape: (1, 10)
┌────────────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬─────┐
│ stat       ┆ pot_num  ┆ train_ener ┆ train_ener ┆ … ┆ val_energy ┆ val_forces ┆ train_time ┆ nit │
│ ---        ┆ ---      ┆ gy_rmse    ┆ gy_atom_rm ┆   ┆ _atom_rmse ┆ _rmse      ┆ ---        ┆ --- │
│ str        ┆ f64      ┆ ---        ┆ se         ┆   ┆ ---        ┆ ---        ┆ f64        ┆ f64 │
│            ┆          ┆ f64        ┆ ---        ┆   ┆ f64        ┆ f64        ┆            ┆     │
│            ┆          ┆            ┆ f64        ┆   ┆            ┆            ┆            ┆     │
╞════════════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═════╡
│ scipy_500_ ┆ 1.581139 ┆ 60.86988   ┆ 1.902184   ┆ … ┆ 2.067155   ┆ 64.50152   ┆ 5.457898   ┆ 0.0 │
│ mean_std   ┆          ┆            ┆            ┆   ┆            ┆            ┆            ┆     │
└────────────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴─────┘

shape: (1, 10)
┌────────────┬─────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────┐
│ stat       ┆ pot_num ┆ train_ener ┆ train_ener ┆ … ┆ val_energy ┆ val_forces ┆ train_tim ┆ nit   │
│ ---        ┆ ---     ┆ gy_rmse    ┆ gy_atom_rm ┆   ┆ _atom_rmse ┆ _rmse      ┆ e         ┆ ---   │
│ str        ┆ f64     ┆ ---        ┆ se         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ f64   │
│            ┆         ┆ f64        ┆ ---        ┆   ┆ f64        ┆ f64        ┆ f64       ┆       │
│            ┆         ┆            ┆ f64        ┆   ┆            ┆            ┆           ┆       │
╞════════════╪═════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════╡
│ scipy_1000 ┆ 3.0     ┆ 27.572229  ┆ 0.861632   ┆ … ┆ 0.944881   ┆ 29.473463  ┆ 588.90222 ┆ 876.0 │
│ _mean      ┆         ┆            ┆            ┆   ┆            ┆            ┆ 4         ┆       │
└────────────┴─────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────┘

shape: (1, 10)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stat      ┆ pot_num  ┆ train_ene ┆ train_ene ┆ … ┆ val_energ ┆ val_force ┆ train_tim ┆ nit       │
│ ---       ┆ ---      ┆ rgy_rmse  ┆ rgy_atom_ ┆   ┆ y_atom_rm ┆ s_rmse    ┆ e         ┆ ---       │
│ str       ┆ f64      ┆ ---       ┆ rmse      ┆   ┆ se        ┆ ---       ┆ ---       ┆ f64       │
│           ┆          ┆ f64       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆           │
│           ┆          ┆           ┆ f64       ┆   ┆ f64       ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ scipy_100 ┆ 1.581139 ┆ 60.898763 ┆ 1.903086  ┆ … ┆ 2.069021  ┆ 64.501739 ┆ 7.296541  ┆ 170.00588 │
│ 0_mean_st ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2         │
│ d         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

Сравниение scipy BFGS на начальном интервале 0.01 и встроенный на том же интервале.

In [12]:
display(df_scipy_001)
display(df_mlip_500)

shape: (5, 9)
┌─────────┬─────────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬─────┐
│ pot_num ┆ train_energ ┆ train_ener ┆ train_forc ┆ … ┆ val_energy ┆ val_forces ┆ train_time ┆ nit │
│ ---     ┆ y_rmse      ┆ gy_atom_rm ┆ es_rmse    ┆   ┆ _atom_rmse ┆ _rmse      ┆ ---        ┆ --- │
│ i64     ┆ ---         ┆ se         ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64        ┆ i64 │
│         ┆ f64         ┆ ---        ┆ f64        ┆   ┆ f64        ┆ f64        ┆            ┆     │
│         ┆             ┆ f64        ┆            ┆   ┆            ┆            ┆            ┆     │
╞═════════╪═════════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═════╡
│ 1       ┆ 0.048972    ┆ 0.00153    ┆ 0.041701   ┆ … ┆ 0.002777   ┆ 0.07243    ┆ 321.804864 ┆ 500 │
│ 2       ┆ 0.043797    ┆ 0.001369   ┆ 0.038913   ┆ … ┆ 0.002834   ┆ 0.069618   ┆ 321.957178 ┆ 500 │
│ 3       ┆ 0.043827    ┆ 0.00137    ┆ 0.036641   ┆ … ┆ 0.002709   ┆ 0.063014   ┆ 330.634391 ┆ 500 │
│ 4       ┆ 0.045151    ┆ 0.001411   ┆ 0.038805   ┆ … ┆ 0.002782   ┆ 0.067986   ┆ 319.621238 ┆ 500 │
│ 5       ┆ 0.048571    ┆ 0.001518   ┆ 0.041818   ┆ … ┆ 0.00296    ┆ 0.074671   ┆ 324.818725 ┆ 500 │
└─────────┴─────────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴─────┘

shape: (5, 8)
┌─────────┬────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┐
│ pot_num ┆ train_ener ┆ train_ener ┆ train_forc ┆ val_energy ┆ val_energy ┆ val_force ┆ train_tim │
│ ---     ┆ gy_rmse    ┆ gy_atom_rm ┆ es_rmse    ┆ _rmse      ┆ _atom_rmse ┆ s_rmse    ┆ e         │
│ i64     ┆ ---        ┆ se         ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│         ┆ f64        ┆ ---        ┆ f64        ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
│         ┆            ┆ f64        ┆            ┆            ┆            ┆           ┆           │
╞═════════╪════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╡
│ 1       ┆ 0.09327    ┆ 0.002915   ┆ 0.077761   ┆ 0.161312   ┆ 0.005041   ┆ 0.120006  ┆ 339.14160 │
│         ┆            ┆            ┆            ┆            ┆            ┆           ┆ 7         │
│ 2       ┆ 0.077083   ┆ 0.002409   ┆ 0.074072   ┆ 0.124319   ┆ 0.003885   ┆ 0.113015  ┆ 364.96913 │
│         ┆            ┆            ┆            ┆            ┆            ┆           ┆ 7         │
│ 3       ┆ 0.086659   ┆ 0.002708   ┆ 0.07386    ┆ 0.12994    ┆ 0.004061   ┆ 0.110455  ┆ 366.34247 │
│         ┆            ┆            ┆            ┆            ┆            ┆           ┆ 4         │
│ 4       ┆ 0.07983    ┆ 0.002495   ┆ 0.060698   ┆ 0.137284   ┆ 0.00429    ┆ 0.089316  ┆ 369.00964 │
│         ┆            ┆            ┆            ┆            ┆            ┆           ┆ 8         │
│ 5       ┆ 0.099781   ┆ 0.003118   ┆ 0.074714   ┆ 0.173422   ┆ 0.005419   ┆ 0.115487  ┆ 359.96218 │
└─────────┴────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┘

In [13]:
display_ensemble_stats(df_scipy_001, "scipy_001_mean")
display_ensemble_stats(df_mlip_500, "mlip_500_mean")

shape: (1, 10)
┌────────────┬─────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────┐
│ stat       ┆ pot_num ┆ train_ener ┆ train_ener ┆ … ┆ val_energy ┆ val_forces ┆ train_tim ┆ nit   │
│ ---        ┆ ---     ┆ gy_rmse    ┆ gy_atom_rm ┆   ┆ _atom_rmse ┆ _rmse      ┆ e         ┆ ---   │
│ str        ┆ f64     ┆ ---        ┆ se         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ f64   │
│            ┆         ┆ f64        ┆ ---        ┆   ┆ f64        ┆ f64        ┆ f64       ┆       │
│            ┆         ┆            ┆ f64        ┆   ┆            ┆            ┆           ┆       │
╞════════════╪═════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════╡
│ scipy_001_ ┆ 3.0     ┆ 0.046064   ┆ 0.001439   ┆ … ┆ 0.002813   ┆ 0.069544   ┆ 323.76727 ┆ 500.0 │
│ mean       ┆         ┆            ┆            ┆   ┆            ┆            ┆ 9         ┆       │
└────────────┴─────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────┘

shape: (1, 10)
┌────────────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬─────┐
│ stat       ┆ pot_num  ┆ train_ener ┆ train_ener ┆ … ┆ val_energy ┆ val_forces ┆ train_time ┆ nit │
│ ---        ┆ ---      ┆ gy_rmse    ┆ gy_atom_rm ┆   ┆ _atom_rmse ┆ _rmse      ┆ ---        ┆ --- │
│ str        ┆ f64      ┆ ---        ┆ se         ┆   ┆ ---        ┆ ---        ┆ f64        ┆ f64 │
│            ┆          ┆ f64        ┆ ---        ┆   ┆ f64        ┆ f64        ┆            ┆     │
│            ┆          ┆            ┆ f64        ┆   ┆            ┆            ┆            ┆     │
╞════════════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═════╡
│ scipy_001_ ┆ 1.581139 ┆ 0.002536   ┆ 0.000079   ┆ … ┆ 0.000094   ┆ 0.004463   ┆ 4.259694   ┆ 0.0 │
│ mean_std   ┆          ┆            ┆            ┆   ┆            ┆            ┆            ┆     │
└────────────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴─────┘

shape: (1, 9)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stat       ┆ pot_num ┆ train_ene ┆ train_ene ┆ … ┆ val_energ ┆ val_energ ┆ val_force ┆ train_tim │
│ ---        ┆ ---     ┆ rgy_rmse  ┆ rgy_atom_ ┆   ┆ y_rmse    ┆ y_atom_rm ┆ s_rmse    ┆ e         │
│ str        ┆ f64     ┆ ---       ┆ rmse      ┆   ┆ ---       ┆ se        ┆ ---       ┆ ---       │
│            ┆         ┆ f64       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│            ┆         ┆           ┆ f64       ┆   ┆           ┆ f64       ┆           ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ mlip_500_m ┆ 3.0     ┆ 0.087325  ┆ 0.002729  ┆ … ┆ 0.145255  ┆ 0.004539  ┆ 0.109656  ┆ 359.88500 │
│ ean        ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9         │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (1, 9)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stat      ┆ pot_num  ┆ train_ene ┆ train_ene ┆ … ┆ val_energ ┆ val_energ ┆ val_force ┆ train_tim │
│ ---       ┆ ---      ┆ rgy_rmse  ┆ rgy_atom_ ┆   ┆ y_rmse    ┆ y_atom_rm ┆ s_rmse    ┆ e         │
│ str       ┆ f64      ┆ ---       ┆ rmse      ┆   ┆ ---       ┆ se        ┆ ---       ┆ ---       │
│           ┆          ┆ f64       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│           ┆          ┆           ┆ f64       ┆   ┆           ┆ f64       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ mlip_500_ ┆ 1.581139 ┆ 0.009381  ┆ 0.000293  ┆ … ┆ 0.02114   ┆ 0.000661  ┆ 0.011904  ┆ 12.053017 │
│ mean_std  ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

Здесь видим уже значительное преимущество scipy

Подберем оптимальный начальный интервал для scipy

In [22]:
df_scipy_intervals = pl.read_csv("results_mtp_scipy_bfgs_intervals.csv")
df_scipy_intervals.select(
    ["interval", "val_energy_atom_rmse", "val_forces_rmse"]
).group_by(pl.col("interval")).mean()

shape: (5, 3)
┌───────────────────┬──────────────────────┬─────────────────┐
│ interval          ┆ val_energy_atom_rmse ┆ val_forces_rmse │
│ ---               ┆ ---                  ┆ ---             │
│ str               ┆ f64                  ┆ f64             │
╞═══════════════════╪══════════════════════╪═════════════════╡
│ [-0.0001, 0.0001] ┆ 0.00252              ┆ 0.060713        │
│ [-0.01, 0.01]     ┆ 0.002844             ┆ 0.069143        │
│ [-0.001, 0.001]   ┆ 0.002552             ┆ 0.06029         │
│ [-0.1, 0.1]       ┆ 0.002813             ┆ 0.069544        │
│ [-1, 1]           ┆ 0.948252             ┆ 29.472281       │
└───────────────────┴──────────────────────┴─────────────────┘

Можно сделать вывод, что для scipy BFGS лучший начальный интревал генерации параметров: [-0.001, 0.001]

Так же посмотрим на результаты для ETN

In [42]:
df_scipy_etn = pl.read_csv("results_etn_scipy_bfgs.csv").drop("success", "final_loss")
df_mlip_etn = pl.read_csv(
    "/Users/peterzarenkov/projects/course_work/optimization_methods_MLP/task1/results/results_etn.csv"
).drop("train_energy_rmse", "val_energy_rmse")

In [43]:
display(df_mlip_etn)
display(df_scipy_etn)

shape: (5, 6)
┌─────────┬───────────────────┬──────────────────┬──────────────────┬─────────────────┬────────────┐
│ pot_num ┆ train_energy_atom ┆ train_forces_rms ┆ val_energy_atom_ ┆ val_forces_rmse ┆ train_time │
│ ---     ┆ _rmse             ┆ e                ┆ rmse             ┆ ---             ┆ ---        │
│ i64     ┆ ---               ┆ ---              ┆ ---              ┆ f64             ┆ f64        │
│         ┆ f64               ┆ f64              ┆ f64              ┆                 ┆            │
╞═════════╪═══════════════════╪══════════════════╪══════════════════╪═════════════════╪════════════╡
│ 1       ┆ 0.008614          ┆ 0.191736         ┆ 0.013874         ┆ 0.277115        ┆ 66.638012  │
│ 2       ┆ 0.008614          ┆ 0.191736         ┆ 0.013874         ┆ 0.277115        ┆ 81.749744  │
│ 3       ┆ 0.008614          ┆ 0.191736         ┆ 0.013874         ┆ 0.277115        ┆ 54.283985  │
│ 4       ┆ 0.008614          ┆ 0.191736         ┆ 0.013874         ┆ 0.277115        ┆ 49.148478  │
│ 5       ┆ 0.008614          ┆ 0.191736         ┆ 0.013874         ┆ 0.277115        ┆ 65.665721  │
└─────────┴───────────────────┴──────────────────┴──────────────────┴─────────────────┴────────────┘

shape: (5, 7)
┌─────────┬─────────────────┬─────────────────┬────────────────┬────────────────┬────────────┬─────┐
│ pot_num ┆ train_energy_at ┆ train_forces_rm ┆ val_energy_ato ┆ val_forces_rms ┆ train_time ┆ nit │
│ ---     ┆ om_rmse         ┆ se              ┆ m_rmse         ┆ e              ┆ ---        ┆ --- │
│ i64     ┆ ---             ┆ ---             ┆ ---            ┆ ---            ┆ f64        ┆ i64 │
│         ┆ f64             ┆ f64             ┆ f64            ┆ f64            ┆            ┆     │
╞═════════╪═════════════════╪═════════════════╪════════════════╪════════════════╪════════════╪═════╡
│ 1       ┆ 0.008552        ┆ 0.191504        ┆ 0.013971       ┆ 0.277264       ┆ 73.915373  ┆ 88  │
│ 2       ┆ 0.008552        ┆ 0.191504        ┆ 0.013971       ┆ 0.277264       ┆ 78.732789  ┆ 97  │
│ 3       ┆ 0.008552        ┆ 0.191504        ┆ 0.013971       ┆ 0.277264       ┆ 96.024937  ┆ 125 │
│ 4       ┆ 0.008552        ┆ 0.191504        ┆ 0.013971       ┆ 0.277264       ┆ 87.987634  ┆ 102 │
│ 5       ┆ 0.008552        ┆ 0.191504        ┆ 0.013971       ┆ 0.277264       ┆ 81.885731  ┆ 90  │
└─────────┴─────────────────┴─────────────────┴────────────────┴────────────────┴────────────┴─────┘

In [45]:
display(df_mlip_etn.mean())
display(df_scipy_etn.mean())

shape: (1, 6)
┌─────────┬───────────────────┬──────────────────┬──────────────────┬─────────────────┬────────────┐
│ pot_num ┆ train_energy_atom ┆ train_forces_rms ┆ val_energy_atom_ ┆ val_forces_rmse ┆ train_time │
│ ---     ┆ _rmse             ┆ e                ┆ rmse             ┆ ---             ┆ ---        │
│ f64     ┆ ---               ┆ ---              ┆ ---              ┆ f64             ┆ f64        │
│         ┆ f64               ┆ f64              ┆ f64              ┆                 ┆            │
╞═════════╪═══════════════════╪══════════════════╪══════════════════╪═════════════════╪════════════╡
│ 3.0     ┆ 0.008614          ┆ 0.191736         ┆ 0.013874         ┆ 0.277115        ┆ 63.497188  │
└─────────┴───────────────────┴──────────────────┴──────────────────┴─────────────────┴────────────┘

shape: (1, 7)
┌─────────┬────────────────┬────────────────┬────────────────┬────────────────┬────────────┬───────┐
│ pot_num ┆ train_energy_a ┆ train_forces_r ┆ val_energy_ato ┆ val_forces_rms ┆ train_time ┆ nit   │
│ ---     ┆ tom_rmse       ┆ mse            ┆ m_rmse         ┆ e              ┆ ---        ┆ ---   │
│ f64     ┆ ---            ┆ ---            ┆ ---            ┆ ---            ┆ f64        ┆ f64   │
│         ┆ f64            ┆ f64            ┆ f64            ┆ f64            ┆            ┆       │
╞═════════╪════════════════╪════════════════╪════════════════╪════════════════╪════════════╪═══════╡
│ 3.0     ┆ 0.008552       ┆ 0.191504       ┆ 0.013971       ┆ 0.277264       ┆ 83.709293  ┆ 100.4 │
└─────────┴────────────────┴────────────────┴────────────────┴────────────────┴────────────┴───────┘

Результаты практически идентичные, но scipy немного лучше, но и времени на обучение требуется в среднем больше на 20 сек.